### PR TITLE
continent map selector

### PR DESCRIPTION
**Pull request by nathancday**
The input Leaflet map selector is working and paired with a tranditional `selectizeInput` so any data filters can watch `input$continent`. Check out the branch, and run it, let me know what you think.

How are the 'better-joining' and 'multi-arc' tasks going?

### CODE REVIEW

**Comment by nathancday** [comment]
@kpivert Let me rebase this onto your most recent merge, looking over that chunk now, nice work!

**Comment by kpivert** [comment]
Sorry it took so long. On the plus side, I can now fix a repo at work that I've been avoiding because of a similar issue. I will start working on the multi-arcs and follow-up with you tomorrow with a status.

**Comment by nathancday** [comment]
LOL, that's great git news! I'm happy this is already improving your day-to-day R life!

Just force pushed a rebased version, so free to merge after review.

I'm gonna start working on the fluidRow graphics now. Happy spatial hacking :neckbeard: !!!

**Comment by kpivert** [comment]
This is fantastic. Thanks @nathancday. Will follow-up tomorrow with an update....and better merge naming.

**Pull request merged**
